
name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          sparse-checkout: .

      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ~/projects/website
            git pull
            git status
            docker build -t website .  
            docker stop website-cont || true
            docker rm website-cont || true
            docker run -p 4000:4000 -d --name website-cont website